baseURL = 'https://fanie-venter.engineer/'
languageCode = 'en-us'
title = 'Fanie Venter'

[params]
  author     = 'Fanie Venter'
  description = 'Software & Systems Engineer based in Auckland, NZ'
  email      = 'georgesventer@gmail.com'
  location   = 'Auckland, New Zealand'
  status     = 'Open to opportunities'
  github     = 'https://github.com/fanieventer'
