baseURL = 'https://fanie-venter.engineer/'
languageCode = 'en-us'
title = 'Fanie Venter - Portfolio'

[params]
  author = 'Fanie Venter'
  description = 'Year 10 Student | Aspiring Aerospace Engineer | Game Developer'
  email = 'georgesventer@gmail.com'
  location = 'Auckland, New Zealand'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true